export const STICKY_COLOR_GRAY = '#AFBCCF'
export const STICKY_COLOR_RED = '#FFAFA3'
export const STICKY_COLOR_BLUE = '#80CAFF'
export const STICKY_COLOR_ORANGE = '#FFC470'
export const STICKY_COLOR_PINK = '#FFBDF2'
export const STICKY_COLOR_LIGHTGRAY = '#E6E6E6'
export const STICKY_COLOR_TEAL = '#75D7F0'
export const STICKY_COLOR_YELLOW = '#FFD966'
export const STICKY_COLOR_VIOLET = '#D9B8FF'
export const STICKY_COLOR_GREEN = '#85E0A3'

export const stickyColorsByName: Record<string, string> = {
	STICKY_COLOR_GRAY,
	STICKY_COLOR_RED,
	STICKY_COLOR_BLUE,
	STICKY_COLOR_ORANGE,
	STICKY_COLOR_PINK,
	STICKY_COLOR_LIGHTGRAY,
	STICKY_COLOR_TEAL,
	STICKY_COLOR_YELLOW,
	STICKY_COLOR_VIOLET,
	STICKY_COLOR_GREEN,
}

export const stickyColorsByHex: Record<string, string> = {
	[STICKY_COLOR_GRAY]: 'STICKY_COLOR_GRAY',
	[STICKY_COLOR_RED]: 'STICKY_COLOR_RED',
	[STICKY_COLOR_BLUE]: 'STICKY_COLOR_BLUE',
	[STICKY_COLOR_ORANGE]: 'STICKY_COLOR_ORANGE',
	[STICKY_COLOR_PINK]: 'STICKY_COLOR_PINK',
	[STICKY_COLOR_LIGHTGRAY]: 'STICKY_COLOR_LIGHTGRAY',
	[STICKY_COLOR_TEAL]: 'STICKY_COLOR_TEAL',
	[STICKY_COLOR_YELLOW]: 'STICKY_COLOR_YELLOW',
	[STICKY_COLOR_VIOLET]: 'STICKY_COLOR_VIOLET',
	[STICKY_COLOR_GREEN]: 'STICKY_COLOR_GREEN',
}
